name: Hugo CI

on:
  push:
    branches:
      - main  # Set to your default branch name
  pull_request:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 'latest'
        extended: true

    - name: Build
      run: hugo --minify  # Add additional flags here if needed

    # Add additional steps for deployment if required
